### PR TITLE
Reverting documentation change

### PR DESCRIPTION
**Pull request by ShmuelTreiger**
### Proposed changes

'systemctl' does not work on my setup (WSL2). 'service' does. I don't see that anything is gained by removing options.

### CODE REVIEW

**Comment by usha-mandya** [comment]
@ShmuelTreiger Thanks for the PR.

@thaJeztah Could you PTAL? 

Believe this update looks good as it provides an option for users who've installed WSL 2 directly. I'm wondering if it's worth updating any other existing pages with the 'service' option if they don't have 'systemctl'? What you do you think?

**Comment by ShmuelTreiger** [comment]
@usha-mandya Just want to emphasize that this was removed in the most recent change to the file, #12439 , I'm just reverting this specific change, it's not something new.

**Comment by thaJeztah** [comment]
@ShmuelTreiger what distro are you running on?

**Comment by ShmuelTreiger** [comment]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
image

**Comment by usha-mandya** [comment]
@ShmuelTreiger Thanks for the PR. The `master` branch has been renamed to `main`. Some of the existing PRs have been automatically closed as a result of this change. Could you create a new PR against our latest docs if the suggested changes are still relevant? Thank you.

**Pull request closed without merging**
