### PR TITLE
Fix links

### PR DESCRIPTION
**Pull request by lamtrinhdev**
## Description

Correct the link in **build-billing.md** for build-details (**build-details.md**) and manage-seats (**manage-seats.md**)

## Reviews

Please review the link for  build-details and manage-seats in build-billing.md 

- [ ] Technical review
- [x] Editorial review
- [ ] Product review

### CODE REVIEW

**Comment by dvdksn** [comment]
Absolute links should not include the content base directory in their paths

**Comment by lamtrinhdev** [comment]
Thank you for your feedback @dvdksn . Let me correct it on another PR.

**Comment by dvdksn** [comment]
What are you trying to do? These links are not broken.

**Comment by lamtrinhdev** [comment]
Sorry for my mistake.

**Pull request closed without merging**
