### PR TITLE
engine: amend 23.0 release notes with ipvlan issue

### PR DESCRIPTION
**Pull request by neersighted**
### Proposed changes

Add mention of https://github.com/moby/moby/issues/44925 and workaround to the release notes.

### CODE REVIEW

**Review by thaJeztah — DISMISSED** [review]
LGTM, thx!

**Comment by thaJeztah** [comment]
@dvdksn ptal

**Comment by neersighted** [comment]
Found a few more punctuation issues, no other changes.

**Review by thaJeztah — APPROVED** [review]
still LGTM

**Pull request merged**
