### PR TITLE
update references to docker engine to v24.0

### PR DESCRIPTION
**Pull request by thaJeztah**

### CODE REVIEW

**Comment by dvdksn** [comment]
hmm, hold on. There are some link errors.

**Review by dvdksn — CHANGES_REQUESTED** [review]
We need to add the stub for api v1.43, and update examples

**Comment by thaJeztah** [comment]
Oh! You're right; I thought I already did the API stub.

Wouldn't surprise me if I already did all of this ... in some branch I forgot about 😂

**Review by dvdksn — APPROVED** [review]

**Comment by thaJeztah** [comment]
thanks for the fix-ups; LGTM

**Pull request merged**
