### PR TITLE
engine: 27.3.0 release

### PR DESCRIPTION
**Pull request by laurazard**
## Description

Add engine 27.3.0 release notes.

## Related issues or tickets

https://github.com/moby/moby/releases/tag/v27.3.0

### CODE REVIEW

**Comment by laurazard** [comment]
cc @dvdksn @thaJeztah (I can't request reviews here 😅)

**Comment by dvdksn** [comment]
Fixed a couple syntax things in the release note, and vendored the new upstreams.

**Review by dvdksn — APPROVED** [review]
LGTM

**Comment by laurazard** [comment]
Thanks!

**Pull request merged**
