### PR TITLE
icon consistency

### PR DESCRIPTION
**Pull request by aevesdocker**

### CODE REVIEW

**Comment by dvdksn** [comment]
❓ does it make sense to add somewhere in our contribution docs an "inventory" of the icons that we've used in our grids? Maybe just a grid like:

```yaml
grid:
  - title: contact_page
    icon: contact_page
```

**Comment by aevesdocker** [comment]
I think it makes sense for a Notion page somewhere, but not sure if we need to add it to our public-facing contribute section - when do users change card content?

**Comment by dvdksn** [comment]
Contributors may not add/change cards, but it would be easier for us (or at least me) to have this reference in the repo directly. Then I don't have to open notion 🐌 and find the right page - it's faster to find the reference among the files that I am already working with.

**Comment by stephaurelio** [comment]
These look really good! I like the idea of a database or inventory of icons used. I'm the opposite of David and I think I'd prefer Notion just because I think it's easier to quickly reference but I'd be fine with whatever option means having a guide so we are consistent with what icons are used where.

**Review by stephaurelio — APPROVED** [review]
Thanks for adding the inventory page! This LGTM. I noticed a small styling error on that page that I'll drop a screenshot of in Slack.

**Pull request merged**
