### PR TITLE
Clarify CLI password behavior when SSO enforced

### PR DESCRIPTION
**Pull request by twelsh-aw**
## Description

- multiple fixes to docs around behavior of passwords when SSO enforced
- security announcement added to outline the planned deprecation

## Reviews

- [ ] Technical review @docker/iam-team
- [ ] Editorial review @docker/docs-team 
- [ ] Product review @francesco-corti

### CODE REVIEW

**Comment by twelsh-aw** [comment]
Not sure about the other vale suggestions. It seems > 10 warnings = CI fail, so will defer to docs team on recommended wording or if can just proceed

**Review by francesco-corti — COMMENTED** [review]
LGTM

**Comment by twelsh-aw** [comment]
@aevesdocker thanks! Let's hold off until tomorrow. Not in any rush and I can circle back for one last look from IAM-team

**Review by ivan-californias — APPROVED** [review]
LGTM

**Comment by twelsh-aw** [comment]
@aevesdocker just following up, but I am planning to merge next week on the 22nd. Not sure if there are extra steps to get it to prod, but there is no rush. Anytime next week works

**Pull request merged**
