### PR TITLE
added chmod command

### PR DESCRIPTION
**Pull request by brccabral**
for those that are new to linux and those that like to just copy commands

### CODE REVIEW

**Review by aevesdocker — APPROVED** [review]
Thanks for this @brccabral , have approved and merged

**Comment by usha-mandya** [comment]
@brccabral Some of the CI checks are failing due to an internal error. This has been fixed in the `main` branch. Could you rebase your PR to fetch those changes? We can merge the PR when when the checks are complete. Thank you.

**Comment by brccabral** [comment]
> @brccabral Some of the CI checks are failing due to an internal error. This has been fixed in the `main` branch. Could you rebase your PR to fetch those changes? We can merge the PR when when the checks are complete. Thank you.

hi, rebase done

**Comment by thaJeztah** [comment]
I think you may have rebased on an outdated branch; I see a lot of foreign commits in here; let me know if you need help

**Pull request closed without merging**
