### PR TITLE
Update run-tests.md

### PR DESCRIPTION
**Pull request by nbarnwell**
The tests literally didn't work for me. I'm not sure what breaking changes appear to have come in since they were first written, but a major problem was that calling `.WithNetwork()` passing in a not-yet-started network would throw an exception. Most of the changes are around coping with that - moving code from ctor to the `InitializeAsync()` method.

### CODE REVIEW

**Comment by craig-osterhout** [comment]
Thank you, @nbarnwell. Your changes fix the exception for me.

Hi @HofmeisterAn, PTAL if you can.

**Comment by HofmeisterAn** [comment]
@nbarnwell can you please share the exception. I will double-check it, but I do not see an issue in the previous code right away.

**Comment by HofmeisterAn** [comment]
I believe the appropriate solution is to set the version to 2.3.0 by using the command `dotnet add package Testcontainers --version 2.3.0`. By doing this, we can avoid running the documentation against an incompatible version of the software. Additionally, we are in the process of implementing module support, which will make the documentation and usage much more straightforward in the future. As part of my responsibilities, I will be updating the Docker documentation once the new version is released.

It should only necessary to update this line:

https://github.com/docker/docs/blob/8275c6f4a6885c82f8f32160e42ddc9dd2127550/language/dotnet/run-tests.md?plain=1#L29

Should I create a PR?

**Comment by nbarnwell** [comment]
I mean, fair enough. But you are opening yourself up to having to revisit this page one day because folks will come here looking for how to use the latest version, only to find the docs stuck at v2.3. I guess choose your pain. :)

**Comment by HofmeisterAn** [comment]
With the next release, the API will be stable. Unfortunately, despite taking great care to avoid introducing breaking changes, I was not completely successful.

> But you are opening yourself up to having to revisit this page one day because folks will come here looking for how to use the latest version, only to find the docs stuck at v2.3.

It is in my own interest to ensure that the Docker documentation is up-to-date. With new TC releases, I am happy to update the documentation as well.

**Pull request closed without merging**
