### PR TITLE
Dockerfile overview added.

### PR DESCRIPTION
**Pull request by SetTrend**
Currently, the navigation panels left and right of the content are are not visible to the reader when certain browser window widths are used (less than 1,000 pixels width).

Apart from that, the navigation tree doesn't come with any help about the different Dockerfile commands.

So, this page serves the purpose of a quick Dockerfile reference overview that can be pinned or bookmarked for easy reference.

### CODE REVIEW

**Comment by SetTrend** [comment]
@thaJeztah : Do you believe we'll get any progress here?

**Comment by thaJeztah** [comment]
Thanks for the ping; I just recalled I had a work-in-progress branch on my machine to address this in a slightly different way. I pushed it as a PR in https://github.com/docker/docker.github.io/pull/13260 (but it's possible it needs more work)

With that PR, the Dockerfile commands will appear in the left-hand navigation, which (I think) may be more "natural", and with the added "bonus" that they will always be available on the left-hand, and not scroll out of view when reading the page.

**Comment by thaJeztah** [comment]
Oh, I may have mis-read the diff; this is a separate page, correct?

Perhaps we should combine the two 🤔

**Comment by SetTrend** [comment]
Exactly. I was hoping people could use my page for bookmarking it so they could quickly branch into what they're searching for.

**Pull request closed without merging**
