### PR TITLE
Speed up inner loop

### PR DESCRIPTION
**Pull request by mikesir87**
### Proposed changes

After playing around with some docs changes, I was getting tired of having to rebuild and restart my containers every time I made a change. So, I decided to take a look at how to fix this. After all, it is a Jekyll project so we _should_ be able to use `jekyll serve`, right?

- Update our custom plugins to not produce file changes if nothing is being changed. Otherwise, we get in a constant file update loop
    - For the fetch_remote plugin, I added a `completion_marker` config option that serves as a filepath to determine if the fetch has already occurred. This prevents resource download from occurring on every file change.
- Add a new `dev` stage to the Dockerfile that starts jekyll serve. It uses a new `dev-start.sh` script to still support the production test use case (which adds the production config file)
- Update the `docker-compose.yaml` file to target this new `dev` stage and expose the livereload port

### Related issues (optional)

None

### CODE REVIEW

**Comment by mikesir87** [comment]
Saw the build failed and it's because of the new `build/bake` docs... all of the same files exist locally _and_ in the remote repo to support the frontmatter. So, there's no way to really know if the files have already been fetched or not by simply using a marker file. Would be nice to have some mechanism to know we've fetched/setup the files without having to do so yet again.

**Comment by mikesir87** [comment]
Same thing for the `https://github.com/moby/buildkit` repo too. The file it's loading already exists with the `fetch_remote` frontmatter.

**Comment by mikesir87** [comment]
Ok. I think it's good to go for a review now. Bring on the feedback! 😄

**Comment by usha-mandya** [comment]
Thank you @mikesir87. 

@crazy-max @thaJeztah Could you PTAL?

**Comment by crazy-max** [comment]
@mikesir87 There are some conflicts, can you rebase please?

> * For the fetch_remote plugin, I added a `completion_marker` config option that serves as a filepath to determine if the fetch has already occurred. This prevents resource download from occurring on every file change.

We discussed about having better cache for `fetch_remote` plugin with @thaJeztah. Your `completion_marker` option might be good if current `ref` still has these files remotely otherwise it will break. It would also skip files newly added remotely.

As we currently download remote resources as zip and some references are not tied to a specific commit (e.g., using a branch like `master`) it's kinda hard to have proper caching. We should instead properly clone the repo and check for changes using git metadata.

> * Add a new `dev` stage to the Dockerfile that starts jekyll serve. It uses a new `dev-start.sh` script to still support the production test use case (which adds the production config file)

Live reload lgtm but I think we should create another PR for this one and first improve caching. WDYT?

**Comment by usha-mandya** [comment]
@mikesir87 @crazy-max As we are gearing up to migrate Docs to Hugo, I'm wondering if we should bring in any changes from this PR to 'main' before the migration. WDYT?

**Pull request closed without merging**
