### PR TITLE
Make specified working directory match Dockerfile

### PR DESCRIPTION
**Pull request by sgriffith3**
### Proposed changes
This change is to update the documentation step specifying the WORKDIR to match the WORKDIR provided in the completed dockerfile a few steps lower.

### CODE REVIEW

**Comment by craig-osterhout** [comment]
Thanks for creating the PR.
Did you run into an issue or misunderstanding with the current Dockerfile, or can you provide a reason for the change?

**Comment by thaJeztah** [comment]
@craig-osterhout I think the issue is that the same page has the "completed" Dockerfile a few lines down, which doesn't match this part (this PR is fixing that); see line 192 of this file

**Comment by sgriffith3** [comment]
@thaJeztah Yes, that was it. I just wanted to eliminate the mismatch.

**Comment by craig-osterhout** [comment]
Thanks @thaJeztah.
@sgriffith3, sorry I misunderstood. Thank you. LGTM

**Comment by craig-osterhout** [comment]
Thanks @thaJeztah.
@sgriffith3, sorry I misunderstood. Thank you. LGTM

**Review by craig-osterhout — APPROVED** [review]

**Pull request merged**
