### PR TITLE
Remove Docker app docs from the CLI reference

### PR DESCRIPTION
**Pull request by usha-mandya**
Signed-off-by: Usha Mandya <usha.mandya@docker.com>

Remove Docker app docs from the CLI reference

### CODE REVIEW

**Comment by usha-mandya** [comment]
@thaJeztah PTAL

**Comment by thaJeztah** [comment]
The YAML files are in https://github.com/docker/docker.github.io/tree/master/_data/docker-app - ISTR we kept these docs up at the time, because the docker 20.10 linux packages still ship with the plugin (but added the "deprecated" options https://github.com/docker/docker.github.io/commit/6047b8f8bd5d3618200898eacc40af64af1b15a0)

**Comment by usha-mandya** [comment]
@thaJeztah Is Docker App still supported on 20.10 linux packages? I thought we've removed Docker App and we don't support it anymore. Could you please confirm?

**Comment by thaJeztah** [comment]
It's still included, as we deprecated it during the 20.10 release (not "supported", as the project itself is marked deprecated, but we don't remove functionality in a patch release). It will be gone from the packages with the 22.xx release though (so: "soon")

**Comment by usha-mandya** [comment]
Thanks @thaJeztah. We'll put this on hold now and merge it as part of Engine 22.x release

**Comment by thaJeztah** [comment]
This will also be handled in https://github.com/docker/docs/pull/16416, so perhaps this one is fine to close (but we can check if there's things missing in that other PR)

**Pull request closed without merging**
