### PR TITLE
Clarify dockerfile instructions

### PR DESCRIPTION
**Pull request by usha-mandya**
Signed-off-by: Usha Mandya <usha.mandya@docker.com>

Carry suggestions from https://github.com/docker/docs/pull/9315/files

closes #9315

### CODE REVIEW

**Review by crazy-max — APPROVED** [review]
LGTM

@thaJeztah I recall there was a thread about a slight difference between BuildKit and legacy builder for some instructions creating layers but can't put my finger on it. Wonder if this was not about squash :thinking:

**Comment by thaJeztah** [comment]
@crazy-max you probably mean https://github.com/moby/moby/issues/38903

**Comment by thaJeztah** [comment]
Oh, and the other difference between BuildKit and classic; `VOLUME` in classic applies volumes during build, but BuildKit doesn't (only changes the image config, but doesn't attach volumes during build)

**Comment by crazy-max** [comment]
> Oh, and the other difference between BuildKit and classic; `VOLUME` in classic applies volumes during build, but BuildKit doesn't (only changes the image config, but doesn't attach volumes during build)

Ah right that was it!

**Comment by thaJeztah** [comment]
I think there's also `WORKDIR`, which for BuildKit follows `USER`, but for the classic builder doesn't

**Pull request merged**
