### PR TITLE
Add details on uploading logos to repositories

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
### Proposed changes

Adds details on ability to add logos to repository listings.

### CODE REVIEW

**Review by aevesdocker — DISMISSED** [review]

**Review by Daniel-Kolev — COMMENTED** [review]
At the moment repository logos are for DVP and DSOS orgs only. These changes might confuse users as some of them won't see the ability to upload a logo. Are we sure we want to describe those paid plan features in the common docs page? If yes, should we at least somehow label them as DVP, DSOSP only?

**Comment by ChrisChinchilla** [comment]
@Daniel-Kolev We don't have any private vs community docs, but followed our standard method here and placed the logo details in a note.

**Review by Daniel-Kolev — APPROVED** [review]

**Comment by ChrisChinchilla** [comment]
I think I need another review from you @aevesdocker

**Review by aevesdocker — APPROVED** [review]
:shipit:

**Pull request merged**
