### PR TITLE
Add link to JP community docs

### PR DESCRIPTION
**Pull request by usha-mandya**
This PR adds a link to the community-translated docs in JP

### CODE REVIEW

**Review by ChrisChinchilla — APPROVED** [review]
Looks good to me. I wonder if we want to use this opportunity to say what you could do if you want to make your own translation?

**Review by thaJeztah — APPROVED** [review]
LGTM as well

let me know if you want more things addressed before merging

**Comment by thaJeztah** [comment]
Yes, I don't think we should _encourage_ this too much, as (even well-intended) such translations often get out of sync, and I frequently run into issues where users use such things and run into issues (outdated instructions etc).

If we _do_ document guidelines, it should probably go into a separate section, and more along the lines of _restrictions_ when using / translating docs, or hosting a mirror of the docs (for offline / internal use). The documentation itself has a permissive license, but that does not include _trademarks_, so we should write guidelines on how to use the content without violating our trademark.

**Review by thaJeztah — APPROVED** [review]
LGTM

**Pull request merged**
