### PR TITLE
Add command for ARM based chip.

### PR DESCRIPTION
**Pull request by kirhist**
There is an example of command for ARM at the beginning but the second command is missing it.

### CODE REVIEW

**Comment by craig-osterhout** [comment]
Hi @kirhist, thanks for sharing the issue. 
There is some issues with the formatting and the flag is not necessary here. For details, see https://github.com/docker/docker.github.io/issues/14517

**Comment by kirhist** [comment]
Hi @craig-osterhout . Without this flag container fails to start with some Python dependency errors. If platform flag is undesirable option then some other options needs to be added.

**Comment by craig-osterhout** [comment]
@kirhist, thank you, I missed that the command hasn't been updated like the previous section.
If you use the following command, do you still get dependency errors? If yes, can you share the error output.

```
docker run -dp 3000:3000 \
   -w /app -v "$(pwd):/app" \
   --network todo-app \
   -e MYSQL_HOST=mysql \
   -e MYSQL_USER=root \
   -e MYSQL_PASSWORD=secret \
   -e MYSQL_DB=todos \
   node:12-alpine \
   sh -c "apk add --no-cache python2 g++ make && yarn install && yarn run dev"
 ```

**Comment by kirhist** [comment]
> @kirhist, thank you, I missed that the command hasn't been updated like the previous section. If you use the following command, do you still get dependency errors? If yes, can you share the error output.
> 
> ```
> docker run -dp 3000:3000 \
>    -w /app -v "$(pwd):/app" \
>    --network todo-app \
>    -e MYSQL_HOST=mysql \
>    -e MYSQL_USER=root \
>    -e MYSQL_PASSWORD=secret \
>    -e MYSQL_DB=todos \
>    node:12-alpine \
>    sh -c "apk add --no-cache python2 g++ make && yarn install && yarn run dev"
> ```

This new command works, thank you.

**Comment by craig-osterhout** [comment]
Thanks for getting back. Do you want to update your PR, or should I close it and open a new one to fix it?

**Comment by kirhist** [comment]
> Thanks for getting back. Do you want to update your PR, or should I close it and open a new one to fix it?

I updated this PR.

**Review by craig-osterhout — APPROVED** [review]
Thank you. LGTM.

**Pull request merged**
