### PR TITLE
Add docs for new expanded Image Details page

### PR DESCRIPTION
**Pull request by mikeparker**
### Proposed changes

Added docs for new expanded Image Details page which now shows vulnerabilities for local docker images.

3 thoughts:
1. I'm wary of adding too much technical information about how images are created, the interaction with base images, hierarchy and security updates. I've tried to strike the right balance but please let me know if any of it is too heavy or light.
2. I haven't added any screenshots. Let me know if this is a good idea. We will be changing the design of this page more in the next few weeks and months so screenshots are likely to be outdated quickly, but maybe an outdated screenshot is better than nothing.
3. This detail could potentially be on it's own page (at some point?). I've left it in place for now.

### CODE REVIEW

**Comment by mikeparker** [comment]
Thanks a lot for the review! I've accepted all the suggestions. Is it OK to merge?

**Review by aevesdocker — APPROVED** [review]
Merging now!

**Comment by StefanScherer** [comment]
Is it also ready to be published? The Desktop tip is already live.

**Comment by aevesdocker** [comment]
Yes, just waiting for someone from my team/ someone with the right permissions, to approve the PR

**Pull request merged**
