### PR TITLE
Publish updates from main

### PR DESCRIPTION
**Pull request by usha-mandya**
Publish updates

### CODE REVIEW

**Comment by thaJeztah** [comment]
LOL, I was just about to open this, and github told me this one was opened;

note that this includes updates for compose that may not yet be in docker desktop (current release), but probably fine to already publish (only some minor changes);

- https://github.com/docker/docs/pull/16444
- https://github.com/docker/docs/pull/16442

**Review by thaJeztah — APPROVED** [review]
LGTM

**Comment by usha-mandya** [comment]
> note that this includes updates for compose that may not yet be in docker desktop (current release), but probably fine to already publish (only some minor changes);

Thanks @thaJeztah.  @aevesdocker are we OK to publish these updates ahead of the Desktop release?

**Comment by aevesdocker** [comment]
@usha-mandya yes good to go, checked with Guillaume. Plus DD 4.16 is out on Thursday so not much of a wait 👍

**Comment by thaJeztah** [comment]
Sounds good to me; looks like there's only two new flags added (and indeed, would only be for a short moment of time)

**Pull request merged**
