### PR TITLE
docker init: update template name in the docs to reflect what's listed in the cli

### PR DESCRIPTION
**Pull request by lizzthabet**
### Proposed changes

Docker Init lists the ASP.NET template as "ASP.NET Core," so I've updated a few references to the template in the docs to reflect this.

### CODE REVIEW

**Comment by lizzthabet** [comment]
@craig-osterhout, would you mind taking a look? thank you!

**Review by craig-osterhout — APPROVED** [review]
LGTM. Thank you!
It appears one more time in containerize.md on line 73. If you don't get it here, I can get it in a follow up.

**Comment by craig-osterhout** [comment]
Forgot you can't merge. I'll merge this and pick it up in a follow up.

**Comment by lizzthabet** [comment]
@craig-osterhout, tysm!

**Pull request merged**
