### PR TITLE
fix broken(anchor) links

### PR DESCRIPTION
**Pull request by rahulpandey70**

### CODE REVIEW

**Comment by dvdksn** [comment]
This change seems to break the links rather than fix them. Can you please describe what issue you've observed?

**Comment by rahulpandey70** [comment]
When i click on prune link, it says page not found(The 'docker/docs' repository doesn't contain the 'config/pruning' path in 'main'.)

**Comment by thaJeztah** [comment]
> When i click on prune link, it says page not found(The 'docker/docs' repository doesn't contain the 'config/pruning' path in 'main'.)

Were you viewing the page on GitHub or on docs.docker.com? If it's on GitHub, then that's probably expected; some of the pages linked to are downloaded while the docs are built and rendered, and cannot he viewed on GitHub; in some other cases we cannot link to the markdown (in this case, the link is a HTML link, which doesn't get converted by our static site builder)

**Comment by rahulpandey70** [comment]
Okay i got it. Now I'm closing PR

**Comment by thaJeztah** [comment]
Thanks! And sorry for the confusion. Perhaps we can fix some of this to make it work on GitHub as well (but we'd have to look into that)

**Comment by rahulpandey70** [comment]
Thanks for the consideration @thaJeztah, If you want to look into that which broken link i'm talking about. Please go this path https://github.com/docker/docs/blob/main/engine/index.md

**Pull request closed without merging**
