### PR TITLE
Merge from main 

### PR DESCRIPTION
**Pull request by aevesdocker**

### CODE REVIEW

**Review by thaJeztah — CHANGES_REQUESTED** [review]
Oh! We probably need to fix the `published` branch first; I saw the "revert" PR yesterday, and anticipated that would cause issues, as this branch effectively can "only move forward". The revert didn't happen on the `main` branch, so now the branches were out of sync, causing the merge conflict here.

**Comment by aevesdocker** [comment]
@thaJeztah I was literally just messaging you to ask for help with this. What do I need to do?

**Comment by thaJeztah** [comment]
I recall we had a similar thing in the past; we _could_ try if "un-reverting" https://github.com/docker/docs/pull/16557 would solve it; that way the code would (hopefully) be in sync again

**Comment by thaJeztah** [comment]
LOL; I was not yet at my computer, and thought: let me write that up ffirst!

**Comment by thaJeztah** [comment]
I opened https://github.com/docker/docs/pull/16564 (hope that will fix it)

**Comment by aevesdocker** [comment]
It worked! Thank you @thaJeztah! 🎉

**Review by thaJeztah — APPROVED** [review]
LGTM!

happy that it worked!

**Pull request merged**
