### PR TITLE
Improve IPv6 documentation

### PR DESCRIPTION
**Pull request by agowa338**
### Proposed changes

Improved the ipv6 documentation.

### Related issues (optional)

Fixes: https://github.com/docker/docker.github.io/issues/8199
https://github.com/moby/moby/issues/37779
https://github.com/moby/moby/issues/35973

### CODE REVIEW

**Comment by L-Hudson** [comment]
@trapier PTAL, thanks!

**Comment by Alkarex** [comment]
Related issue https://github.com/moby/moby/issues/36954

**Comment by slxiao** [comment]
Any progress about the merging? I'm looking forward to this fix.

**Comment by thaJeztah** [comment]
@arkodg ptal

**Pull request closed without merging**
