### PR TITLE
Proposition in startup-order.md

### PR DESCRIPTION
**Pull request by ionelmc**
Hey, So yes, I've made that tool. I'm not sure about the text changes have the right wording but I'm pretty sure holdup is way better than what's suggested there. It has checks for files, tcp/unix sockets, http, https and postgresql (that handles the infamous `FATAL:  the database system is starting up` error).

### CODE REVIEW

**Comment by usha-mandya** [comment]
@ulyssessouza - Could you PTAL?

**Comment by ionelmc** [comment]
Any update?

**Comment by ionelmc** [comment]
Hello @ulyssessouza @usha-mandya, I've rebased this, is it acceptable in this form?

**Comment by ionelmc** [comment]
Well?

**Pull request closed without merging**
