### PR TITLE
Add Scout go links

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
### Proposed changes

Adds convenience go links for Scout

### CODE REVIEW

**Review by thaJeztah — APPROVED** [review]
"LGTM"

but I agree with your earlier mention of these not being much more memorable than the links they point to, so slightly wondering if it would be fine to use the regular URLs (unless we want to redirect to anchors in future)

**Comment by thaJeztah** [comment]
Perhaps minor nit; should we sort the list of `/go/` redirects in the file, to make it easier to find them?

**Comment by ChrisChinchilla** [comment]
@thaJeztah I felt having them by section might be easier? I think for now I will create them and let the team decide if they want to use them or not and we can always remove them after a trial period to see if they are used at all?

**Comment by thaJeztah** [comment]
> @thaJeztah I felt having them by section might be easier? I think for now I will create them and let the team decide if they want to use them or not and we can always remove them after a trial period to see if they are used at all?

Ah, yes that makes sense as well. I guess as long as we stick to one approach, it works. "hunting down" redirects in a list that becomes longer can be a pain 😅

**Pull request merged**
