### PR TITLE
[DDB-35] Add fully qualified links to 4.25.0 and beyond

### PR DESCRIPTION
**Pull request by neonima**
## Description

In order for links to work correctly in docker desktop, it is needed to have fully qualified links. This PR fixes all links down to version 4.25.0.

## Related issues or tickets
https://docker.atlassian.net/browse/DDB-35

## Reviews

- [x] Technical review
- [ ] Editorial review
- [ ] Product review

### CODE REVIEW

**Review by aiordache — APPROVED** [review]

**Comment by lorenrh** [comment]
Indeed, as @aevesdocker mentioned, the release highlights are saved on the [appcast](https://desktop.docker.com/win/main/amd64/appcast.xml) and [metadata](https://desktop.docker.com/win/main/amd64/metadata.json) directly. So changing them here, won't have any effect in the release highlights we see on the app.

**Comment by maxcleme** [comment]
Indeed, we need to change the appcast and metadata files. @neonima did you spot a broken highlights within the in-app update?

**Comment by neonima** [comment]
> Indeed, we need to change the appcast and metadata files. @neonima did you spot a broken highlights within the in-app update?

Closing then :D - in the past some links were broken (most likely relative URLs)

**Comment by lorenrh** [comment]
We can update the release highlights, but it won't really matter anymore, as we won't be showing 4.28.0 for updates 🤔   we should however check the links in when setting the highlights... but we have a ticket here https://docker.atlassian.net/browse/DKP-1217 

I really think we can move DDB-35 to done.

**Comment by neonima** [comment]
@lorenrh awesome thank you :D

**Pull request closed without merging**
