### PR TITLE
Add scout recommendations command

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
# Proposed changes

Adds the missing `scout recommendations` command

### CODE REVIEW

**Comment by dvdksn** [comment]
It seems like the `recommendations` subcommand is missing from the child commands section:

image

I think generate updated YAML for the parent command, `docker_scout.yaml`, fixes this.

**Comment by ChrisChinchilla** [comment]
Updated, over to you @eunomie

**Comment by eunomie** [comment]
Isn't it already covered by #16971 ?

**Comment by ChrisChinchilla** [comment]
@eunomie First I heard of that PR! But, yes it is, I will get it merged

**Pull request closed without merging**
