### PR TITLE
New screenshot for Docker Extensions v4.25.0

### PR DESCRIPTION
**Pull request by Frezzle**
### Proposed changes

Some things have changed, such as Build tab renamed to Create, and the sidebar has changed since v4.22.0.

It's also good to update because new extensions appear top of the list, so they get some promotion here in the docs.

This PR changes the extensions page to this:

Screenshot 2023-10-20 at 17 03 19

Screenshot 2023-10-20 at 17 03 32

It used to look like this:

Screenshot 2023-10-20 at 17 12 11

Screenshot 2023-10-20 at 17 12 19

### Related issues

This is one of the UI changes that warranted this screenshot change: https://github.com/docker/pinata/pull/24689

### CODE REVIEW

**Comment by Frezzle** [comment]
I noticed the image size went from 166KB to ~1MB -- probably not ideal for web. Do we have a process/tool we commonly use for making our docs images a good size while keeping good quality?

**Review by dvdksn — CHANGES_REQUESTED** [review]
hi, please compress using [https://](https://squoosh.app/). I recommend converting to webp.

**Comment by Frezzle** [comment]
> hi, please compress using [squoosh](https://squoosh.app/). I recommend converting to webp.

Thanks, done!

**Review by dvdksn — APPROVED** [review]
LGTM! Thanks!

**Comment by dvdksn** [comment]
🤦🏻 just realized this is probably not released yet.

**Pull request merged**
