### PR TITLE
iptables documentation : restrict incoming by destination port

### PR DESCRIPTION
**Pull request by hervenicol**
Documentation on how to restrict incoming traffic by destination port.

### Proposed changes

Restrict incoming traffic by destination port is a bit tricky, and I did not find expected information in the documentation.
So tried to give a short explanation with an example.

### CODE REVIEW

**Comment by usha-mandya** [comment]
@djs55 Could you PTAL? Thanks

**Comment by hervenicol** [comment]
Direct link to rendered pages:
* original: https://docs.docker.com/network/iptables/
* from PR: https://deploy-preview-14283--docsdocker.netlify.app/network/iptables/

**Review by djs55 — APPROVED** [review]
Looks good to me. Also worth showing to @thaJeztah

**Comment by hervenicol** [comment]
@thaJeztah , @djs55 , @usha-mandya , up to you. :shrug:

**Comment by usha-mandya** [comment]
Close and reopen PR to trigger build checks

**Comment by usha-mandya** [comment]
Thanks for the nudge @hervenicol!

@thaJeztah Could you PTAL?

**Pull request closed without merging**
