### PR TITLE
docs: enhance html output

### PR DESCRIPTION
**Pull request by jawys**
### Proposed changes

- Removed some leading space in a code formatting because I found the following issue in html rendering:

screenshot of issues in networking docs

- Replaced double $ before terminal commands in code blocks for consistency

### CODE REVIEW

**Comment by jawys** [comment]
checked the deploy preview:
grafik
LGTM

**Comment by craig-osterhout** [comment]
Thanks @jawys. I haven't looked too closely at it, so I may be wrong, it looks like the `$$` is there to differentiate running a command in the container as opposed to the host.
It probably should be made more clear using different syntax. We're currently trying to standardize this, so if any suggestions, please let us know.

The change for removing the leading space looks good. If you want to revert the `$$` changes, I can merge this.

**Comment by jawys** [comment]
Oh I see, maybe I replaced the `$$` too fast :D

Previously I stumbled upon the following part, which looks indeed as if there is some mixup there:

grafik

---

What I like about the single `$` is the fact, that the "Copy code to clipboard" button removes the `$` from the code block which I can then paste into the terminal. This saves me time while quickly fiddling stuff out.

Nevertheless Ill fixup the commit and remove the replacements as you wish.

**Comment by craig-osterhout** [comment]
Thanks @jawys.

> @craig-osterhout if you agree I`d like to add the following:
>
> @@ -461,7 +461,8 @@ Start a container and view eth0 and both v4 & v6 routing tables:
> ```console
> $ docker run --net=ipvlan140 --ip6=2001:db8:abc2::51 -it --rm alpine /bin/sh
> 
> -$ ip a show eth0
> +# Inside the container
> +$$ ip a show eth0

I suggest open this in a separate issue/PR because it will require more scrutiny or an SME to approve, which will take longer. 

Thanks again for the feedback about the copy to clipboard feature. We're currently trying track down all the different prompts and standardize them in order to fix this.

**Review by craig-osterhout — APPROVED** [review]
LGTM

**Comment by jawys** [comment]
> I suggest open this in a separate issue/PR because it will require more scrutiny or an SME to approve, which will take longer.

Thanks @craig-osterhout. I now opened another PR (#16109) for these changes.

**Comment by jawys** [comment]
> Thanks again for the feedback about the copy to clipboard feature. We're currently trying track down all the different prompts and standardize them in order to fix this.

Another suggestion for the container shell syntax: 
If one would use `#$`instead of `$$` as prefix, the "copy to clipboard" would help to just copy a comment into my host shell instead of the commands which shall be executed in the container's shell.

What do you think?

**Pull request merged**
