### PR TITLE
ENGDOCS-1507

### PR DESCRIPTION
**Pull request by aevesdocker**
PR makes it clear that the documentation refers to Compose V2 and reduces the frequency on the banner

### CODE REVIEW

**Comment by aevesdocker** [comment]
@usha-mandya As per our sync, would something like this work?

**Comment by usha-mandya** [comment]
Thanks @aevesdocker. I was wondering if it makes sense to remove it from the other topics  such as Service profiles, GPU support, Extend services, and Networking?

**Comment by aevesdocker** [comment]
GPU support, yes for sure, I'll remove it from there. But I also have other feedback from another Captain saying that the visibility of the migration was not clear, so I'm going to leave it on the other pages. Networking is very popular page, and Extend services may also get an increase in viewings with the latest release of Compose. Profiles is also on an upwards trajectory as I increased the visibility of it in the Compose spec!

**Comment by usha-mandya** [comment]
Sure.  Please go ahead and remove the banner from the GPU topic. We can go back and update the pages if we start getting more feedback on any of these.

**Review by usha-mandya — APPROVED** [review]

**Pull request merged**
