### PR TITLE
DS-63 using WSL doesn't need to run the admin windows service

### PR DESCRIPTION
**Pull request by elapuyade**
### Proposed changes

https://docker.atlassian.net/browse/DS-69 and https://docker.atlassian.net/browse/DS-70 change the requirement to run the windows service when using WSL2.

This PR updates the documentation according to that.

### Related issues (optional)

https://docker.atlassian.net/browse/DS-63

### CODE REVIEW

**Review by aevesdocker — APPROVED** [review]
Thanks @elapuyade LGTM

Do you want this published today, or does it coincide with Docker Desktop 4.17 release?

**Comment by elapuyade** [comment]
The corresponding code changes should be integrated for 4.17. I'll merge this here when I'm sure the code goes into 4.17 as well.

**Comment by elapuyade** [comment]
Hi Allie, I just saw you merged this. The code change has finally not made it to 4.17, it will be in 4.18.

Is this merged for 4.17?

**Comment by aevesdocker** [comment]
Hi @elapuyade, ah, thanks for letting me know. It hasn't made it into production yet, so I've just reverted the merge.

**Comment by elapuyade** [comment]
The corresponding code is now merged in pinata main.

**Comment by aevesdocker** [comment]
Thanks @elapuyade. I need to wait until the DD 4.18 release day to merge this into docs. The new PR is here with the DD4.18 milestone attached

https://github.com/docker/docs/pull/16799

**Pull request merged**
